### ISSUE TITLE
Slider loses tracking outside of widget

### ISSUE THREAD

**Issue by lawik** [boydm/scenic#102]
### What problem does this feature solve?

This is a user experience thing I noticed while playing with the example (solid instructions for getting up and running, by the way, good job).

The slider elements (dragging a marker on a line) stop tracking your mouse's horizontal position if you move outside of the bounds of the widget. It stops dragging but will resume if you re-enter the bounds.

This felt awkward so I verified with some system components and at least on Mac (volume settings for example) they will, as I suspected keep tracking even if you go somewhere else vertically. As long as you keep the button pressed you have control of the slider.

I think this will mostly make the widget feel better. But it should also improve accessibility since it will no longer require the user to be quite as precise. So I think this would be a better default behavior.

### What is your proposed solution?

Once you press down on the element to grab a hold of it you should keep that hold until you release, even if you go out-of-bonds on the vertical axis. I have not checked if this would straight forward or more complex in the code yet. This way just something I noticed while trying the feel of the widgets.

Let me know if anything seems unclear and I'll try to clarify :)

**Comment by boydm** [comment]
Did you try this with the master version? I think it has been fixed already, but would be good to double-check as I'm about to release 0.9.0

**Comment by lawik** [comment]
I'll give that a whirl then :)

**Comment by lawik** [comment]
Yup, this is fixed in the current master. And here I thought I had found something. No wonder I couldn't figure out why this was happening from the master code :)

Nice work.

**Comment by boydm** [comment]
Thank you!
Check out version 0.9.0 in an hour or so.
Much improved docs and...
Support for Nerves! At least on the Raspberry Pi anyway...

**Comment by boydm** [comment]
Ok. only sort of. Scenic and the glfw driver 0.9 are published. The nerves drivers are not because I stuck trying to get the publishing tool to build the docs - it insists on building the c code first, but that fails as it needs to be cross compiled.

I'll figure that out in the morning.

later...

**Comment by lawik** [comment]
Very fair :)
