### ISSUE TITLE
Circular(ish) dependency on glfw

### ISSUE THREAD

**Issue by pragdave** [boydm/scenic#114]
I'm trying to test an updated version of scenic_new with a correspondingly updated version of scenic.

The problem is that the code generated by scenic_new includes 

~~~ elixir
{:scenic, github: "pragdave/scenic", branch: "add-specs"},
{:scenic_driver_glfw, "~> 0.9"}
~~~

But `:scenic_driver_glfw` also has a dependency on scenic, which it satisfies from hex. As a result, I get an error on deps.get

When I try to use :override to force just my version to be used, I get explosions inside glfw

~~~
20:46:42.323 [error] GenServer :glfw terminating
** (UndefinedFunctionError) function Scenic.Cache.request_notification/1 is undefined or private
    (scenic) Scenic.Cache.request_notification(:cache_put)
    (scenic_driver_glfw) lib/glfw.ex:82: Scenic.Driver.Glfw.init/3
    (scenic) lib/scenic/view_port/driver.ex:153: Scenic.ViewPort.Driver.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:after_init, #PID<0.4413.0>, {700, 600}, %{module: Scenic.Driver.Glfw, name: :glfw, opts: [resizeable: false, title: "dave"]}}}
State: nil
~~~

Is there some magic I'm missing?

**Comment by boydm** [comment]
Add `override: true` to your scenic dependency.

Technically, you only need to take a dependency on the driver, which will pull in scenic. To me, that seems confusing for beginners, so I put both of them in there.

**Comment by pragdave** [comment]
Then I get the glfw error, I think...

**Comment by boydm** [comment]
glfw.ex line 82 is where it tries to communicate with the cache. Is the cache process running?

    `Cache.request_notification(:cache_put)
`

**Comment by boydm** [comment]
Oh wait. I know what that is.

I just commented out the deprecated calls for v0.10. The 0.9 glfw driver is still calling the old apis.

I just updated the master branch of the driver to use the new api. Refer to that one please.

https://github.com/boydm/scenic_driver_glfw.git

**Comment by pragdave** [comment]
And that was indeed the magic I sought :)
