### ISSUE TITLE
Feature request: Root scene should receive untranslated mouse input

### ISSUE THREAD

**Issue by axelson** [boydm/scenic#119]
### What problem does this feature solve?

It can be confusing to new users that cursor input is not received by the root scene, yet keyboard input is. The current behavior confused me initially and has also confused others ([example](https://elixirforum.com/t/scenic-not-receiving-click-events/18939))

### What is your proposed solution?

Allowing the root scene to receive any cursor input that is not captured by any other scene. I think this makes sense logically, although if it doesn't make sense for any reason than maybe it's best to just add a transparent rectangle to the example project to help people with cursor input.

Although an alternative is to educate people on the behavior of mouse input, e.g. in the scenic_new project (https://github.com/boydm/scenic_new/pull/22)

**Comment by boydm** [comment]
First reaction is that this would be OK. I'm going to try to think through any possible negatives first tho.

Either way, I'm neck-deep in a related, but different codebase for at least another week or two. So we have a little time to think this through.

**Comment by boydm** [comment]
In v0.11 there are new functions in the Scene module that solve this. From any scene, can use Scene.local_to_global/2 to translate the received point (in local coordinates) into global coordinates. Scene.global_to_local/2 does the opposite.

**Comment by axelson** [comment]
👍 I think that the capture syntax makes this a little clearer/more explicit as well.
