### ISSUE TITLE
Feature Request: fill with gradient

### ISSUE THREAD

**Issue by ConnorRigby** [boydm/scenic#122]
### What problem does this feature solve?
I often find myself wanting to apply a gradient to a shape, rather than just a single color.

### What is your proposed solution?
Maybe an API like this:
```
graph
|> rectangle( {100, 200}, fill: {:gradient, [0x6db1ec, 0x35a274], 90})
```

where `fill`'s options are `{:gradient, list_of_colors, angle}`

**Comment by ConnorRigby** [comment]
AAAND i just found this in the docs. Sorry for the noise.
https://hexdocs.pm/scenic/Scenic.Primitive.Style.Paint.LinearGradient.html

**Comment by boydm** [comment]
Ha! Funny. Super glad you are using it tho.
