### ISSUE TITLE
Button text not centered in button

### ISSUE THREAD

**Issue by ConnorRigby** [boydm/scenic#131]
This seems to be a font issue where button text is not rendered in the center of thee button. This looks
okay normally, but on bigger buttons it is a little strange. 

![screenshot from 2019-02-27 22-46-39](https://user-images.githubusercontent.com/21150830/53576960-a6399400-3b29-11e9-90ef-14d145fab3f2.png)

**Comment by crertel** [comment]
Is your expectation that the centerline of the text be vertically centered, or like what do you think it should look like?

**Comment by ConnorRigby** [comment]
My exception for larger buttons would be to center the text in the button vertically.

From Boyd on Slack:

> It is using a fixed percentage for the vertical alignment, but should calculate the position based on the height of the chosen font.

**Comment by boydm** [comment]
The proper fix for this is in the works. Currently planning to get it into v.10, possibly as early as this week. I'll put a note here once it gets into master.

**Comment by crertel** [comment]
@ConnorRigby maybe it would help if I clarified my intent:

![Some font measurements](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F0BzCQdutE8gumVE9NYmg5cU83N2s%2Fanatomy.png).

**Comment by boydm** [comment]
Fixed in Master. Will go out in v.10
