### ISSUE TITLE
Installing Courier New font gives invalid name error

### ISSUE THREAD

**Issue by quantumproducer** [boydm/scenic#154]
### Checklist

- [ ] Check other issues and make sure that it is not reported yet.

### Versions and Environment

~/elixir -v
Erlang/OTP 21 [erts-10.2.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 21)
~/

Scenic:

* scenic (Hex package) (mix)
  locked at 0.9.0 (scenic) 129594f9

OS:

OSX
```text

```

### Steps to reproduce

https://github.com/QuantumProductions/scenic_font_test

### Expected Behavior
I tried to install a Courier New font following https://github.com/boydm/scenic/blob/master/guides/custom_fonts.md

### Actual Behavior

In GameOver.ex there is

```
  @font_folder :code.priv_dir(:play) |> Path.join("/static/fonts")
  @custom_font_hash "UYe2ryfLUpczug9LKyrTxPYGSYTimnPHzpSMbC6UF0M"
  @custom_metrics_path :code.priv_dir(:scenic_example)
           |> Path.join("/static/fonts/Courier New.ttf.metrics")
  @custom_metrics_hash Scenic.Cache.Support.Hash.file!(@custom_metrics_path, :sha)
```

#### Stack Trace

```
==> play
make: Nothing to be done for `all'.
Compiling 4 files (.ex)

== Compilation error in file lib/scenes/game_over.ex ==
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1    
    
    The following arguments were given to IO.chardata_to_string/1:
    
        # 1
        {:error, :bad_name}
    
    Attempted function clauses (showing 2 out of 2):
    
        def chardata_to_string(string) when is_binary(string)
        def chardata_to_string(list) when is_list(list)
    
    (elixir) lib/io.ex:461: IO.chardata_to_string/1
    (elixir) lib/path.ex:512: Path.join/2
    lib/scenes/game_over.ex:9: (module)
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
could not compile dependency :play, "mix compile" failed. You can recompile this dependency with "mix deps.compile play", update it with "mix deps.update play" or clean it with "mix deps.clean play"
```

Name of font does not seem to be accepted. I downloaded from https://www.wfonts.com/font/courier-new

<details>

```bash

```

</details>

**Comment by boydm** [comment]
Custom fonts and loading and all that stuff has been extensively re-written in Scenic v0.10.

Please see the upgrade docs here: https://hexdocs.pm/scenic/upgrading_to_v0-10.html, then let me know if it makes sense. The custom font thing is aa little trick as you will need to use the truetype_metrics tool to generate a metrics file, then store that alongside your custom font.

Is well worth it tho as all sorts of goodness is unlocked. Needs a how-to-do-custom-fonts blog post...

**Comment by quantumproducer** [comment]
Thanks! Since there is an update I will close the issue for now. Will try again later with latest version.
