### ISSUE TITLE
Add typespec to all the functions

### ISSUE THREAD

**Issue by yordis** [boydm/scenic#17]
Type specs are quite useful for understanding the data structures being used on the functions and so on.

Better to add it now than later

**Comment by boydm** [comment]
Agree. Been adding them, but many left to go...

**Comment by confucius** [comment]
Line 103 of lib/scenic/view_port.ex

  @spec stop(config :: ViewPort.Config.t()) :: {:ok, pid}
  def start(%ViewPort.Config{} = config) do

Funny :-)

**Comment by boydm** [comment]
@SPEC stop(config :: ViewPort.Config.t()) :: {:ok, pid}
def start(%ViewPort.Config{} = config) do

is now fixed in master

**Comment by boydm** [comment]
Making lots of progress on this.

**Comment by crertel** [comment]
I've found `ERL_COMPILER_OPTIONS="warn_missing_spec" mix compile --force 2>&1 ` to be helpful for this sort of work.

**Comment by crertel** [comment]
```
crertel@attenborough:~/projects/scenic/scenic$ ERL_COMPILER_OPTIONS="warn_missing_spec" mix compile --force 2>&1 | grep warning: | wc -l
636
```

So, we have some work ahead of us. :)

**Comment by crertel** [comment]
@boydm Something I noticed when working on this was that a lot of the functions (I think some of the input stuff exhibitied this) have a catch-all case. Because _reasons_, dialyzer works with the most permissive type, and so any catchall function (which would take an `any()`) basically negates the input-half of utility dialyzer can give us.

So, can we remove those catchalls?

**Comment by boydm** [comment]
Ah! Here's the deal. As I was writing Scenic, I was also learning all the nifty subsystems at the same time. The reason there are so many all() types - and the reason there are not enough specs- is that I didn't know any better!

So I'd love the see a recommendation on the right way to do it. I'll stop adding any() specs when I know what to put in there instead.

And what do you recommend for the type of the id on a primitive? That really is intended to be any term you want to use to identify the item...

**Comment by boydm** [comment]
This is largely done in v0.11
