### ISSUE TITLE
ex_doc version is outdated

### ISSUE THREAD

**Issue by axelson** [boydm/scenic#174]
Can the ex_doc version used to publish releases be updated? The newest ex_doc version includes much better search.

Ideally for me #170 would be merged so I could send a PR that explicitly updates the ex_doc version so that when publishing the docs the publisher doesn't need to run `mix deps.update ex_doc themselves). Alternatively we could bump the minimum version in mix.exs (although I could see that geting annoying very quickly).

**Comment by boydm** [comment]
updating now...

**Comment by boydm** [comment]
resolved in master

**Comment by axelson** [comment]
Great, thanks!
