### ISSUE TITLE
Dropdown freezing UI

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#183]
Having the dropdown component open when scenic re-renders the dropdown causes the entire UI to freeze.

**Comment by boydm** [comment]
That isn't enough information for me to look into it. Version? Other circumstances? What other code is going on?

Can you provide more please? This might require a pointer to code exhibiting the issue.

**Comment by vacarsu** [comment]
What I'm doing is subscribing to a sensor when the scene initializes, and at some point the sensor publishes a list of addresses which devices are located. If the dropdown is being interacted with when the dropdown gets updated with new addresses the whole application freezes and nothing can be interacted with.

``` elixir
@initial_dropdown_opt [{"Addresses", :load_addresses}]
@address_dropdown dropdown_spec(
    {@initial_dropdown_opt, :load_addresses},
    id: :dropdown_addresses,
    t: {500, 80},
    theme: Theme.preset(:primary)
)

@graph Graph.build(font: :roboto, font_size: 16, theme: @theme)
    |> add_specs_to_graph([
      @address_dropdown
    ])

def init(_, _) do
    Sensor.subscribe(:address_sensor)
    {:ok, %{
      graph: @graph,
      addresses: [],
      selected_address: nil,
    }, push: @graph}
  end

def handle_info({:sensor, :data, {:address_sensor, addresses, _}}, %{graph: graph, selected_address: selected_address} = state) do
    avail_addresses =
      addresses
      |> Enum.map(fn {_a, %{address: address}} -> {address, :"#{address}"} end)
      |> Enum.concat(@initial_dropdown_opt)
    graph =
      graph
      |> Graph.modify(:dropdown_addresses, &dropdown(&1, {avail_addresses, :load_addresses}, []))

    {
      :noreply,
      %{state | graph: graph, addresses: avail_addresses},
      push: graph
    }
```

**Comment by boydm** [comment]
That's interesting.

So you are changing the contents of the dropdown while it is in the dropped-down state. I'm not sure I considered that case. The dropdown will have captured the input while it is "down". If it is being reset, I suspect it is never releasing that capture.

We'd have to dig into the code that updates the contents and make sure it does a input release. Probably by putting it into the "up" state. his could be visually messy tho.

Needs some thought as to what the right answer is.

**Comment by boydm** [comment]
Hey. Another question for you. Regarding the scenic_sensor library, it is really just a simple pub/sub system. Thinking I should have called it scenic_pub_sub. I'm tempted to republish it under that name going forward and deprecate the old one. It would still be there, but any new work would be under the new name. What do you think? Worth it to ease up on the confusion around the name?

**Comment by vacarsu** [comment]
Yes, I think scenic_pub_sub would be better. Since it isn't strictly used for devices/sensors.

**Comment by boydm** [comment]
Cool. I was thinking the same thing.

I'm going to try to put some time in to Scenic over the holidays. I'll put that on the list.

**Comment by vacarsu** [comment]
@boydm I was thinking instead of renaming Scenic.Sensor to Scenic.PubSub. How about Scenic.Service? Since services are something that are subscribed to.

**Comment by boydm** [comment]
I'm open to Scenic.Service, although Scenic.PubSub is more consistent with Phoenix naming. For that reason alone should probably be pubsub. What do you think?

**Comment by vacarsu** [comment]
Coming from Angular land after many years, the Service name makes a lot of sense to me. However the name PubSub is very clear as to what it is. I'm just thinking of having to type PubSub.subscribe  and PubSub.publish every time seems odd to me. Service.subscribe Service.publish sounds and feels much better to me. But that is just my opinion.

**Comment by boydm** [comment]
I get it. Although you could always `import PubSub`, and then just call publish and subscribe directly...

Gut says the right thing to do is follow the Phoenix precedent, and then rely on import to reduce typing if that works for you. Then, if there is any ambiguity that needs to be resolved, just don't do the import and type out the module.

**Comment by vacarsu** [comment]
Sounds good to me.

**Comment by vacarsu** [comment]
With capture_input no longer fully necessary in v0.11 would you like me to close this issue @boydm?

**Comment by boydm** [comment]
Yes please.
