### ISSUE TITLE
Support use of name: option to register component processes

### ISSUE THREAD

**Issue by tiger808** [boydm/scenic#184]
Have `Component.add_to_graph/3` honor the `name:` option in its options argument to specify the registration of the component's process when it is started.

### What problem does this feature solve?
This is a convenience feature to allow developers to easily use the `GenServer` naming option to register their component processes.

As a developer I can write:
```
graph =
  state.graph
  |> custom_component(data, id: :primitive_id, name: :scene_name)
```
...and when the `custom_component` process is started it will be registered under `:scene_name`.

I thought that I read in the documentation / code / personal communication that Scenic supported the GenServer naming facility in this way. But I cant find it. This is just how I expected it to work. Several parts of the code look like they were written for this to work.

### What is your proposed solution?
The API is as shown above where any name value supported by `GenServer` should work.

I think that it is just a simple patch to `Primitive.apply_standard_options/2` and `Primitive.apply_style_options/2`. The `name:` option should be treated the same as the `id:` option. If passed through to the `start` function, it "should just work".

I think Boyd blessed the idea, so I'll try a fix and submit a PR if it works.

**Comment by boydm** [comment]
Yes. This is a good solution. We just need to search the code to see if the `:name` option is used for anything else. If not, then it is probably a leftover and good to use. I hope so!

**Comment by boydm** [comment]
Closing as I think this is resolved in master. Feel free to re-open if not.
