### ISSUE TITLE
Horizontal Lines when changing to scene rendering text

### ISSUE THREAD

**Issue by BWheatie** [boydm/scenic#187]
# Checklist

- [ x ] Check other issues and make sure that it is not reported yet.

### Versions and Environment

Elixir:

1.9.1-otp-22

Erlang:

22.0.7

Scenic:

0.10.2

OS:
MacOs 10.15.3

### Steps to reproduce

Change to a scene which renders text either in a component and the component will have horizontal lines or text primitive where the whole screen will have horizontal lines.

### Expected Behavior

No horizontal lines
![Screen Shot 2020-02-25 at 4 33 28 PM](https://user-images.githubusercontent.com/12969891/75299107-d3cb2300-57f9-11ea-8d84-d05f5fde7725.png)
![Screen Shot 2020-02-25 at 6 02 18 PM](https://user-images.githubusercontent.com/12969891/75299114-d6c61380-57f9-11ea-9f61-b0ee31dcfbff.png)

It is resolved once you leave the scene. It also _only_ happens when you change to the a scene with text. It does not happen when it is in root. 

Also happens when you resize a scene with text.

**Comment by BWheatie** [comment]
Not sure if this is a core, font, or driver issue. If we think it needs to go elsewhere I can move it.

**Comment by boydm** [comment]
Yikes. Do you have a pointer to a simple sample that exhibits this? Would help speed me toward a repro...

**Comment by BWheatie** [comment]
https://github.com/BWheatie/font_render_issue

**Comment by boydm** [comment]
![lines_screenshot](https://user-images.githubusercontent.com/176561/75503534-bdf87080-5a3a-11ea-966d-2ec3b5c58abc.png)

OK. So it looks fine on my machine.

This is probably an issue in the driver that does the rendering and will be specific to your setup. What machine/OS/graphics card, etc are you using?

**Comment by Eiji7** [comment]
Looks good for me as well on `openSUSE Tumbleweed`.

**Comment by axelson** [comment]
Hmmm, on Arch Linux I just get a white screen in the window with no text.

**Comment by BWheatie** [comment]
I am on MacOS. Radeon Pro 560X 4 GB Intel UHD Graphics 630 1536 MB

**Comment by Eiji7** [comment]
@axelson One scene is listening for right key and second on left key. It looks like the author want to do some multi step setup or something like that.

**Comment by boydm** [comment]
@BWheatie Hi Ben. Still not sure what to do about this issue without a repo. Do you have any other graphics issues with your machine? The lack of repos makes me wonder if there is something else going on.

**Comment by BWheatie** [comment]
Did the one I linked to not help? Have no had any issues. I have heard from others they have had the same issue.
