### ISSUE TITLE
Static textures swapping to incorrect textures.

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#192]
When rendering static textures as components, when the UI re-renders the previously loaded textures seem to be swapping to more recently loaded textures. On another re-render some textures render correctly but others swap to a different one still. I haven't figured out why this is happening I'm sure I'm probably doing some wrong here.

OS:

```text
Linux

```

### Steps to reproduce

Create several icon components like so, and re-render them.

```elixir
defmodule App.Component.Icon.DeleteForever do
  use Scenic.Component

  alias Scenic.Graph
  import Scenic.Primitives

  @icon_path :code.priv_dir(:mip_at)
    |> Path.join("/static/icons/delete_forever_white.png")

  @icon_hash Scenic.Cache.Support.Hash.file!(@icon_path, :sha)

  @graph Graph.build()
    |> rect({48, 48}, fill: {:image, @icon_hash}, scale: 0.5)

  def verify(data), do: {:ok, data}

  def init(_, _) do
    Scenic.Cache.Static.Texture.load(@icon_path, @icon_hash)

    {:ok, %{graph: @graph}, push: @graph}
  end
end
```

### Expected Behavior

The component should always render the correct texture. at the path specified.

### Actual Behavior

Components rendered "seemingly" random textures that were loaded more recently.

**Comment by vacarsu** [comment]
I got this working properly with passing scope: :global option.

**Comment by boydm** [comment]
Ah yes. the scope. Glad it worked out.
