### ISSUE TITLE
Any plans on adding multiple backends

### ISSUE THREAD

**Issue by D4no0** [boydm/scenic#193]
Do you have any plans on adding different backends like Vulkan/OpenglES/Metal?

**Comment by boydm** [comment]
The current version uses OpenGLES, so that is already good go.

Supporting backends like Vulkan/Metal/DirectX/others is very doable, it just needs a reason for it. If you have a strong need or are willing to take a crack at that work your self please reach out. Otherwise it stays in the undetermined-when future work bucket.

**Comment by D4no0** [comment]
OpenGL ES is of importance at the moment, if it works correctly. As of future Vulkan should be added for sure, since all modern gpu support it.

Thank you.

**Comment by boydm** [comment]
I understand how important Vulkan is to support. The question is more if someone wants it enough to either help do the work or to help pay for it.

**Comment by D4no0** [comment]
Currently my priority is to run scenic on Android, after that there is a high possibility I will help to add support for Vulkan.

**Comment by boydm** [comment]
Ah. That is very interesting. I think the first hard part is getting Erlang to run at all. Last time I looked (a while ago) that was very difficult. If you get Erlang running at all, then the rest is very doable.

**Comment by D4no0** [comment]
Yeah that was quite a pain, but I got the OTP-23 running on Android 9.0.

Here is the forked version that works on ART devices:
https://github.com/D4no0/erlanglauncher

**Comment by boydm** [comment]
OK. Next question: Do Ports work? If yes, then the step is to create a scenic driver that supports that works. Maybe the existing GLFW version will already work?? I don't know. Might need minor changes.

If it is an all new driver, then I'd probably base it off of the rpi version. The main.c file would need to be largely re-written as that is where all the device-specific initialization lives. The rest should be good.

**Comment by D4no0** [comment]
Ok, it seems to be working, the code for initialization:

```
#define GLFW_INCLUDE_ES2
#include <GLFW/glfw3.h>

int main()
{
    glfwInit();

    glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API);
    glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);
    GLFWwindow* window = glfwCreateWindow(1920, 1080, "Window Title", NULL, NULL);
    glfwMakeContextCurrent(window);

    while (1) {
        glClearColor(0.0f, 1.0f, 1.0f, 1.0f);
        glClear(GL_COLOR_BUFFER_BIT);
        glfwSwapBuffers(window);
    }
}
```
On touching the screen the output in logs is:
`V/threaded_app: New input event: type=2`

On window focus change, there are also events:
```
V/threaded_app: WindowFocusChanged: 0x6fdb41ca00 -- 0
V/threaded_app: WindowFocusChanged: 0x6fdb41ca00 -- 1
```

**Comment by boydm** [comment]
Wow. That is very exciting. Do you have it drawing? Can you post a screenshot?
That would make my day. Very cool.

**Comment by D4no0** [comment]
Yes it is drawing, however I noticed that the merge stopped. It seems that the GLFW API is not very suitable for touch events and the changes were not merged completely.

I have found GLFM, a different library inspired by GLFW that is specialized for Android and IOS, I tried to run an example however there are some errors coming from native VM side which may prove a big pain to fix.

**Comment by D4no0** [comment]
Ok, now this is very promising. I got the application working and it responds to touch events very well.
Here are some screenshots:
![image](https://user-images.githubusercontent.com/22370804/85700290-e6406500-b6e4-11ea-82a5-a64a9fe72f34.png)

And after moving using the touch:
![image](https://user-images.githubusercontent.com/22370804/85700328-f0626380-b6e4-11ea-9d86-74371e8b3d47.png)

**Comment by D4no0** [comment]
Goddamn it even works with external keyboard connected via usb, so in theory it should work with virtual keyboard no problems

**Comment by boydm** [comment]
Uh yeah. That is fantastic

**Comment by crertel** [comment]
Hell yeah!
