### ISSUE TITLE
Examples of multiple ViewPorts?

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#197]
Is there any examples out there for multiple view ports? This is a necessity for an app I am working on. I have tried doing ViewPort.start, but because ViewPort is already running it errors. Passing in multiple configs to {Scenic, viewports: [main_viewport_config]}, does not seem to work either.

**Comment by vacarsu** [comment]
I got it working, I had to change the name parameter of the GLFW driver.

**Comment by boydm** [comment]
Oh good! I was just about to dig up an example.

You can also pass multiple drivers to a single viewport. This would give you two windows mirroring the same content. You may need to play with the names to avoid conflicts just like with the multiple viewports.

Also, the name on the driver is a convenience for when you are looking in :observer. I'm pretty sure you can just omit the name and let it be anonymous, which avoids the whole problem in the first place...

**Comment by boydm** [comment]
Didn't actually mean to close the issue in case others wanted to see the response. Hit the wrong button.

If things are good, could you please close it in a day or two?

Thanks,

--Boyd
