### ISSUE TITLE
Scenic dependencies on Windows?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [boydm/scenic#206]
Background
-----

I have been playing around with [Scenic](https://hexdocs.pm/scenic/welcome.html) to make a desktop app across multiple environments. While the [`Install dependencies`](https://hexdocs.pm/scenic/install_dependencies.html#content) for Ubuntu are outdated and don;t work for the latest LTS (v20) I was still able to figure out the packages and install it on Ubuntu Linux.

However ... there is nothing for Windows.

Questions
---

1. Does Scenic even work on Windows?
2. If so, what are the dependencies? What need I to install?

**Comment by cortfritz** [comment]
flame,

take a look here: https://medium.com/@jeffborch/running-the-scenic-elixir-gui-framework-on-windows-10-using-wsl-f9c01fd276f6

**Comment by Fl4m3Ph03n1x** [comment]
So, Scenic does not support Windows nor will it run on a Windows system. 
Are you aware of any alternatives to Scenic that would run on a Windows system?

**Comment by hakanai** [comment]
I would like to know the same.
