### ISSUE TITLE
Using scissor with a scrollbar renders over components outside of scissored area

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#213]
I have a group with content that I scissor to hide content that doesn't fit. I have a scrollbar to scroll the content inside the group. The problem here is that if the content is very large it will render over content above the group. The content itself is hidden however it's as if the content still get's rendered above the outside content.

Here is a screenshot of the group scroll to the top notice I can still hover and click the System tab at the top.
![PXL_20210408_163939575](https://user-images.githubusercontent.com/11384972/114066073-29bd2780-9850-11eb-8743-dd40ba8ec180.jpg)

If I scroll down causing the group's content to translate up, the I can no longer hover over the System tab or click it.
![PXL_20210408_163909265](https://user-images.githubusercontent.com/11384972/114066181-48bbb980-9850-11eb-9fb9-189d803e765d.jpg)

**Comment by boydm** [comment]
First... Awesome looking project!

I'm not sure what to say without digging into the draw orders. Is the title bar drawn before or after the contents of the window? You should draw it after in the root scene.

**Comment by vacarsu** [comment]
Well, it's a bit complicated as I have a Tabs Component that renders the Scenes based on which tab you have selected.

Here is how the tabs and scenes are rendered
``` elixir
def init(%{active_tab: active_tab, tabs: tabs}, _) do
    graph =
      Graph.build(font_size: 20)
      |> add_scene_refs(active_tab, tabs)
      |> add_tab_buttons(tabs)

    {:ok, %{graph: graph, active_tab: active_tab, tabs: tabs, selected_tab_pid: nil}, push: graph}
  end
```

I do render the tab buttons after the scene is rendered. I also, however, rerender parts of that table when certain things change. Could this be placing the content over the tabs?

**Comment by vacarsu** [comment]
I just realized, when the active_tab changes I do not rerender the tabs after rendering the tab's view. This is what is causing the content to be blocking the tabs. :)

**Comment by boydm** [comment]
Ah!

I was just typing up something like that.

Glad you found it!

**Comment by boydm** [comment]
UI is hard
