### ISSUE TITLE
Mouse Scroll wheel event

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#214]
Are mouse scroll wheel events sent to the viewport at all? I see in scenic_driver_glfw in input.ex starting on line 310
However it isn't clear how to capture this event?

``` elixir
def handle_port_message(
        <<
          @msg_mouse_scroll_id::unsigned-integer-size(32)-native,
          x_offset::float-native-size(32),
          y_offset::float-native-size(32),
          x_pos::float-native-size(32),
          y_pos::float-native-size(32)
        >>,
        state
      ) do
    debounce_input({:cursor_scroll, {{x_offset, y_offset}, {x_pos, y_pos}}}, state)

    {:noreply, state}
  end
```

**Comment by boydm** [comment]
Some events, especially mouse movement related events (scroll wheel counts) can generate a TON of messages very quickly. One of my goals was to use as little energy as possible, so these events are not sent unless the scene indicates that it wants them.

So... You need to request the scroll event from the viewport.

See ViewPort.capture_input
https://hexdocs.pm/scenic/Scenic.ViewPort.html#capture_input/2

When you are done with it and no longer want the flood of messages, you can release it with release_input

This api is being updated in the upcoming release, but the general idea is the same. The scene needs to ask for events other than mouse button events, which should be the only ones on by default.

If you dig into the built-in components, you'll see that they request and release input types as appropriate.

**Comment by vacarsu** [comment]
@boydm thanks for the response. If I have multiple scrollbars rendered, is it possible to release the captured input from outside of the component that currently has it captured? At the moment you must pass in a context to ```release_input```. If The second scrollbar gains "focus" and must ```release_input``` from the first scrollbar, would I need to save the context of the first scrollbar elsewhere to be referenced within the second scrollbar? Is there any plans to have some form of a multi-capture input system, where many components can capture input events?

**Comment by boydm** [comment]
Depends on what you are going for.

If I was doing a scroll bar, I would do something like this...

1) Start with a "normal" state of only the mouse buttons captured.
2) When there is a mouse button down inside the scroll bar component, then I would capture mouse move (:cursor_pos) and drag around as appropriate.
3) When the the mouse button changes to unpressed, then I would release the :cursor_pos capture. This should then work with multiple scroll bars.

This behavior is somewhat similar to now the slider component works. You need to decide if you want the thumb to move around when the mouse is outside the original component or not. (The slider does...)

The slider could also capture key events and do key-based page_up / page_down sorts of things. Maybe home and end as well? That would get weird tho with multiple scoll bars showing simultaneously.



This is a relatively

**Comment by boydm** [comment]
The parent scene probably wants to capture the scroll wheel though and then send update messages down to the scroll bars so that they update state correctly.

This is doable in the current version (see the the radio group) but I think the API for it is confusing. That is another one that is being overhauled in the update. Sending messages to child components will be easier.

I'm getting close to having a first pass of the update that I can push into a branch. When I do, you should take a good look at this part of the API and give me some feedback on it to make sure it does what you want.

**Comment by boydm** [comment]
Oh. and to answer the original question, I don't remember if you can release the input from outside the component. I think so??? Would need to check tho.

**Comment by vacarsu** [comment]
@boydm I'm trying to capture the ```:cursor_scroll``` event when the component renders as I don't do any handle any inputs at the moment which is what generates a context to use in ```capture_input```. How can I generate a context manually?

**Comment by boydm** [comment]
Yeah. This is part of why I'm changing that part of the API. You won't need a context in v.11

>  I don't do any handle any inputs in the component that renders the scroll bar.

In general tho, Scenic favors a model where the event handling and rendering happen in the same component. The component can then send messages up to it's parent to act on. This provides much better isolation and error recovery. Feels like maybe the scrollbar should handle it's own input and then send {:scroll, ...} messages to the parent to act on.

**Comment by vacarsu** [comment]
Yes, I can do that. However I still have the same issue in needing to capture the ```:cursor_scroll``` event before an ```handle_input``` is called. I think I might have to wait for the new version. It would be nice to handle the scenario where I could capture the ```:cursor_pos```, and change the capture of the ```:cursor_scroll``` to the  scroll bar container the mouse is currently in. Much like how MacOS handles window scrolling.

**Comment by boydm** [comment]
Makes sense. I'm getting pretty close to being able to push up an alpha version of v.11 I think in the next week or two.

Has been a ton of work...

**Comment by vacarsu** [comment]
Awesome! Thank you for al the hard work you're doing in this space. I've been working on this decentralized control system project with scenic for just over a year, and have really enjoyed using scenic. The project is just about finished and ready to be used in the synthesis of Astatine for cancer treatment.

**Comment by boydm** [comment]
That project sounds awesome. I'd love t know more about it. You willing to do a call to chat?

**Comment by vacarsu** [comment]
Sure I can do a call. When works best for you?

**Comment by boydm** [comment]
Hmmm. How to do this. Wish Github allowed private DMs. Can you ping me on Twitter so we can DM there? Or maybe LinkedIn is easier...

twitter:@boydmulterer
or
https://www.linkedin.com/in/boydmulterer/

**Comment by vacarsu** [comment]
It seems you can't be messaged on twitter.

**Comment by boydm** [comment]
Sorry. Let me know your twitter handle. I'll follow you back and then you can. or @me in something so I know who you are.

**Comment by vacarsu** [comment]
twitter:@vacarsu1

**Comment by boydm** [comment]
This should now be fixed and functioning the way you want in the v0.11 branch. Please confirm, then close the issue if it works for you.

**Comment by vacarsu** [comment]
Yes, working in v0.11 now.
