### ISSUE TITLE
`Scene.release_input/2` may not be working

### ISSUE THREAD

**Issue by crertel** [boydm/scenic#257]
### Checklist

- [x] Check other issues and make sure that it is not reported yet.

### Versions and Environment

Elixir:

```bash
# elixir -v
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]

Elixir 1.12.2 (compiled with Erlang/OTP 24)
```

Erlang:

```bash
# erl -v
Erlang/OTP 24 [erts-12.0.3] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit]
```

Scenic:

```text
# mix deps | grep scenic
* scenic 0.11.0-beta.0 (Hex package) (mix)
  locked at 0.11.0-beta.0 (scenic) cace35ef
* scenic_driver_local 0.11.0-beta.0 (Hex package) (mix)
  locked at 0.11.0-beta.0 (scenic_driver_local) 8812762a
```

OS:

```text
Linux [hostname redacted] 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Steps to reproduce

Sample scene:

```elixir
defmodule Example.Scene do
  @moduledoc """
  This is a minimal scene that will publish received keyboard events to the console.
  """
  use Scenic.Scene

  @input_classes [:codepoint, :key]

   @impl Scenic.Scene
  def init(scene, _param, _opts) do
    :ok = request_input(scene, @input_classes)
    { :ok, scene }
  end

  @impl Scenic.Scene
  def handle_input( {:key, {:key_x, 0, _}}, _ctx, scene ) do
    :ok = release_input(scene, @input_classes)
    IO.inspect(:key_x, label: "Cancel input: ")
    {:noreply, scene}
  end

  def handle_input( evt, _ctx, scene ) do
    IO.inspect(evt, label: "Input: ")
    {:noreply, scene}
  end
end
```

### Expected Behavior

Pressing `x` key should unsubscribe from keyboard events; no further keypresses should register.

### Actual Behavior

Pressing `x` key prints message but other keyboard events still get delivered to scene.

### Additional Comments

I checked over in the [viewport code](https://github.com/boydm/scenic/blob/b2e57b50737443d8fb7a6d7ef2e88ef704cf42c2/lib/scenic/view_port.ex#L1292), but am unsure if that's the cause of this.

**Comment by vacarsu** [comment]
`request_input/2` should be followed by `unrelease_input/2`. `release_input/2` is for `capture_input/2`.

**Comment by crertel** [comment]
@vacarsu excellent!

That seems to solve the problem, closing.

(Ran into this while working on tutorials, so honestly it's a good catch.)
