### ISSUE TITLE
Document Cache Module

### ISSUE THREAD

**Issue by zacck** [boydm/scenic#29]
I noticed that the cache module doesn't have documentation, opening this issue as a notification of intent

see #5 for more details

**Comment by boydm** [comment]
Great! If you have any questions, please feel free to reach out.

The point of the scope feature is to manage the life of an item in memory when two different scenes want to use it. This could be a scene, and then a component. Or maybe something managed by the developer.

We don't want to load and unload the item repeatedly if it is still in use. So each process tries to "claim" the item in the cache. Doing so adds a "reference" that it is in use. It only gets cleaned up when all the refs go to zero.

The :global scope basically says to ignore all that and keep it in memory all the time.

**Comment by crertel** [comment]
@boydm should the items get cleared once refcount hits 0, or should we periodically be sweeping for 0 refcount items and clearing them as we get around to them?

Or am I misunderstanding how this should be working?
