### ISSUE TITLE
Using a custom font fails with `Unknown message: 0x38`

### ISSUE THREAD

**Issue by tcoopman** [boydm/scenic#37]
I’m trying to load a custom font like this:

    Scenic.Cache.Hash.compute(File.read!(@font_path), :sha) |> IO.inspect()
    Scenic.Cache.File.load(@font_path, @font_hash) |> IO.inspect()
    Scenic.Cache.File.read(@font_path, @font_hash) |> IO.inspect()

    graph =
      Graph.build(font: @font_hash, font_size: 24)

This is the output when using the font:

"cu1h9EqFbnBMyCyDDqtWtMh2lOw"
{:ok, "cu1h9EqFbnBMyCyDDqtWtMh2lOw"}
{:ok,
 <<0, 1, 0, 0, 0, 20, 1, 0, 0, 4, 0, 64, 71, 80, 79, 83, 39, 13, 154, 194, 0, 4,
   82, 12, 0, 0, 117, 60, 71, 83, 85, 66, 177, 57, 193, 22, 0, 4, 199, 72, 0, 0,
   0, 146, 76, 84, 83, 72, ...>>}
Unknown message: 0x38
WARNING Excess message bytes! 313343

So it looks like loading/reading the file works fine, but when I use it I get the error message.
It’s a ttf font.

(I've first posted this [on the forum](https://elixirforum.com/t/using-a-custom-font-in-scenic-fails-with-unknown-message-0x38/16420), but as this probably is a bug (or lacking documentation) I'm putting it here as well)

**Comment by boydm** [comment]
I'll dig into it.

**Comment by boydm** [comment]
Which font are you loading?

**Comment by tcoopman** [comment]
I wanted to take a look at it, but I see that `0.8` isn't published on `hex`?
I've tried using the latest masters but got this compilation error:

```bash
Erlang/OTP 21 [erts-10.0.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

==> scenic_sensor
Compiling 1 file (.ex)
Generated scenic_sensor app
==> scenic
Compiling 78 files (.ex)
Generated scenic app
==> scenic_driver_glfw
mkdir -p priv/prod
cc -O3 -std=c99 `pkg-config --static --cflags glfw3 glew` -fPIC -o priv/prod/scenic_driver_glfw c_src/main.c c_src/comms.c c_src/nanovg/nanovg.c c_src/utils.c c_src/render_script.c c_src/tx.c `pkg-config --static --libs glfw3 glew` -lGL -lm -lrt
c_src/render_script.c:102:36: error: ‘M_PI’ undeclared here (not in a function); did you mean ‘NVG_PI’?
   static const float        TAU  = M_PI * 2;
                                    ^~~~
                                    NVG_PI
make: *** [Makefile:43: priv/prod/scenic_driver_glfw] Error 1
could not compile dependency :scenic_driver_glfw, "mix compile" failed. You can recompile this dependency with "mix deps.compile scenic_driver_glfw", update it with "mix deps.update scenic_driver_glfw" or clean it with "mix deps.clean scenic_driver_glfw"
==> scenic_2048
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. If you are using
Ubuntu or any other Debian-based system, install the packages
"build-essential". Also install "erlang-dev" package if not
included in your Erlang/OTP version. If you're on Fedora, run
"dnf group install 'Development Tools'".


```

**Comment by boydm** [comment]
tcoopman: what OS are you using?

**Comment by boydm** [comment]
Actually, just try it from master again please. (and tell me which OS you are using). I switched to NVG_PI, which should be defined.

**Comment by tcoopman** [comment]
I'm on Archlinux. Latest master fixes the compiling error and the font issue.
Thanks!

**Comment by boydm** [comment]
Yay! Thank you for letting me know.

I can already see that I'm going to have a whole pile of VMs with different builds of Linux in them...

**Comment by tcoopman** [comment]
I think you could get a long way with some docker images?

**Comment by tcoopman** [comment]
It is possible to run X within a docker container. Basically you share the X11 socket with the container and use that.
I haven't used it myself either, so not sure how easy/hard it is and not sure how travis handles it.
