### ISSUE TITLE
Fill in Documentation

### ISSUE THREAD

**Issue by boydm** [boydm/scenic#5]
Many of the components are not yet documented.

If you would like to help out, as you get familiar with Scenic, please pick a module that needs documentation. Submit an issue here to claim that you are working on it, then go for it.

I will be working on as many of these (and the guides) as I can over the next few weeks. There is still quite a bit tho.

**Comment by und0ck3d** [comment]
Hey @boydm. Let me take this opportunity to thank you for the amazing work and effort you put into bringing this awesomeness, really appreciated!

I just found a dead link in the "General Overview" to the "Scene Overview" but I think it's probably to [Structure of a Scene](https://hexdocs.pm/scenic/scene_structure.html)? If this is correct and you want me to fix it no worries.

**Comment by boydm** [comment]
0.9.0 Will have a lot of improvements in Documentation

**Comment by boydm** [comment]
I think this is pretty much done in v0.11
