### ISSUE TITLE
Fix linting errors

### ISSUE THREAD

**Issue by milmazz** [boydm/scenic#53]
If you want to contribute to this project, probably a _good first issue_ to solve would be reducing the number of _warnings_, _refactoring opportunities_, _code readability issues_, or _software design suggestions_ reported by [credo](https://github.com/rrrene/credo).

Now the report includes the following findings:

![screen shot 2018-09-19 at 10 21 03 am](https://user-images.githubusercontent.com/34700/45763618-6f646700-bbf6-11e8-9ccc-afbecc09c386.png)

So, that's too much work for just one person (@boydm) to handle.

If you haven't use `credo` before, you can do the following:

```console
cd scenic
mix deps.get
mix credo
```

If you want to find more suggestions you can try:

```console
mix credo --strict
```

For more information, please check [credo](https://github.com/rrrene/credo) project.

**Comment by yordis** [comment]
@milmazz @boydm I commented out the `credo` command on Travis because I didn't know what direction do you want to take.

I always use Credo (with the default setup, no changes) but it is up to you @boydm

**Comment by milmazz** [comment]
@yordis have you look at https://ebertapp.io/ (from Plataformatec)? It would be nice to include that service here. Ebert includes `credo` as a linter (among other), the configuration that they use is [this one](https://github.com/plataformatec/linters/blob/master/.credo.exs) /cc @boydm

**Comment by yordis** [comment]
@milmazz yep I use `ebertapp` for the OS projects.

I wouldn't create any config thought, even with the formatter I go with the default options unless I definitely have a strong opinion about it, I tend to do not get cut of on changing so much those files that become contra-productive as a contributor.

**Comment by crertel** [comment]
I'll open a PR to maybe fix some of these--for future reference, Credo by default we've found to just kinda kvetch about too many things. We might want to setup a default sane config.

**Comment by crertel** [comment]
Alright, that's the first chunk. If we're happy with that, I'll proceed with the full mop-up.

**Comment by crertel** [comment]
@boydm Want me to roll up the rest of the credo stuff if possible?

Also, is there an IRC or something where we can talk and I can get fast guidance? :P

**Comment by boydm** [comment]
Catch me on Slack (@boydm) in the Elixir thingy.
 
Or twitter. (@boydmulterer)
 
-----Original Message-----
