### ISSUE TITLE
Credo Appeasement: Code Readability

### ISSUE THREAD

**Issue by crertel** [boydm/scenic#64]
Next chunk of credo issues to resolve are modules missing a `@moduledoc` tag.

This issue is about adding in ones--probably `@moduledoc false` for now--to shutup credo and give people a place to start writing in more documentation.

**Comment by boydm** [comment]
Thank you for diving in!

**Comment by crertel** [comment]
Note to self--several of the module files have little comments at the top, like one-line "Helper module for fooing bars."

I'm using those as tentative moduledocs until we get a better idea, if they're available.

**Comment by crertel** [comment]
Alright, that one's up. :)

Once this is in, will do the other one.
