### ISSUE TITLE
Updating creation date to ISO-8601 format

### ISSUE THREAD

**Issue by grahamhay** [boydm/scenic#85]
The structure and format of the commented out lines of metadata at the top of files is currently inconsistent, and in some cases incomplete, or missing.

As a first step in establishing a canonical structure and format for the metadata at the top of files - the various date formats used for the creation date have been re-written in an ISO-8601 compliant format.

This will allow an automated pass over the files in the repository to identify files where the metadata is currently inconsistent, incomplete, or missing.

An Issue (to be raised after this one) will propose for adoption if found to be satisfactory - a simple structure and format for the metadata at the top of files.

Note: The choice of the ISO-8601 date format is to eliminate the several ambiguities that arise from the inevitable mixed use of US mm/dd/yy formats and other formats used around the globe.

**Comment by boydm** [comment]
This change was merged
